services:
  - type: worker  # Worker service
    name: fal-gram-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PAYMENT_PROVIDER_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ENVIRONMENT
        value: production
    # REMOVED health check and PORT - not supported for workers
    autoDeploy: true
    numInstances: 1
    region: frankfurt

# (Keep your database config if needed)
